### PR TITLE
fix: planstorage functionality

### LINKED ISSUE #217: error storing tfplan file to gcp storage
see   https://github.com/diggerhq/francios-tests/actions/runs/4910811353/jobs/8768305578

Testing with `upload-plan-destination: gcp` option.

`digger plan` comment results with:

image

### PR DESCRIPTION
**Pull request by fleroux514**
closes #217 

- `planStorage.StorePlan()` now stores plan files along the lock files in storage buckets
image

- stored plan files are deleted when a project's lock is released

### CODE REVIEW

File: pkg/utils/plan_storage.go [hunk 1]
```diff
@@ -91,14 +102,18 @@ func (gps *GithubPlanStorage) RetrievePlan(planFileName string) (*string, error)
...
+	plansFilename, err = gps.ZipManager.GetFileFromZip(plansFilename, storedPlanFilePath)
 
 	if err != nil {
 		return nil, fmt.Errorf("error extracting plan: %v", err)
 	}
 	return &plansFilename, nil
 }
 
+func (gps *GithubPlanStorage) DeleteStoredPlan(storedPlanFilePath string) error {
+	return nil
```
Comment (fleroux514) [inline pkg/utils/plan_storage.go:114]: `Not sure how to address here

**Review by Spartakovic — APPROVED** [review]
