### PR TITLE
wait until dynamodb table is active

### LINKED ISSUE #212: failing to run digger plan on first run
dynamoDB race condition occurs during the first run in a fresh account

```
Run curl -sL [https://github.com/diggerhq/digger/releases/download/${actionref}/digger-Linux-X64](https://github.com/diggerhq/digger/releases/download/$%7Bactionref%7D/digger-Linux-X64) -o digger
GitHub context parsed successfully
Digger config read successfully
2023/05/06 01:31:02 Using AWS lock provider.
2023/05/06 01:31:03 Successfully connected to AWS account ***, user Id: AIDAWFYLQIVMMBIFWN32Q
Lock provider has been created successfully
2023/05/06 01:31:03 Following projects are impacted by pull request #1
dev
staging
GitHub event processed successfully
GitHub event converted to commands successfully
2023/05/06 01:31:03 Following commands are going to be executed:
project: dev: commands: "digger plan", 
project: staging: commands: "digger plan", 
Lock SRV-Tech/serene-hospital-infra#dev
DynamoDB Table DiggerDynamoDBLockTable has ben created
2023/05/06 01:31:05 Failed to run digger plan command. error locking project: ResourceNotFoundException: Requested resource not found
Failed to run commands. failed to run digger plan command. error locking project: ResourceNotFoundException: Requested resource not found
Error: Process completed with exit code 8.
```

### PR DESCRIPTION
**Pull request by motatoes**
closes #212

This was tested in this pipeline with additional print statements in a region where DDB did not exist and it was created successfully and also locking performed

https://github.com/motatoes/testdggrdemo/actions/runs/4947076430/jobs/8845976623

```
Lock motatoes/testdggrdemo#default
checking status, current status is CREATING err is <nil>
 checking status, current status is CREATING err is <nil>
checking status, current status is CREATING err is <nil>
checking status, current status is CREATING err is <nil>
checking status, current status is CREATING err is <nil>
checking status, current status is CREATING err is <nil>
checking status, current status is CREATING err is <nil>
checking status, current status is CREATING err is <nil>
checking status, current status is ACTIVE err is <nil>
DynamoDB Table DiggerDynamoDBLockTable has been created
project motatoes/testdggrdemo#default locked successfully. PR # 3
```

### CODE REVIEW

File: pkg/aws/dynamo_locking.go [hunk 1]
```diff
@@ -16,6 +16,32 @@ type DynamoDbLock struct {
...
+func (dynamoDbLock *DynamoDbLock) waitUntilTableCreated() error {
+	input := &dynamodb.DescribeTableInput{
+		TableName: aws.String(TABLE_NAME),
+	}
+	status, err := dynamoDbLock.DynamoDb.DescribeTable(input)
+	cnt := 0
+
+	fmt.Printf("checking status, current status is %v", status.Table.TableStatus)
+	for err != nil && *(status.Table.TableStatus) != "ACTIVE" {
+		time.Sleep(1)
```
Comment (Spartakovic) [inline pkg/aws/dynamo_locking.go]: this is nanoseconds

Comment (motatoes) [reply pkg/aws/dynamo_locking.go]: good catch, there are so many docs pages where this is not documented correctly

**Review by Spartakovic — APPROVED** [review]
